// <auto-generated />
using System;
using KonferansSalonu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonferansSalonu.Migrations
{
    [DbContext(typeof(ConferencedbContext))]
    [Migration("20260224213444_InitialCleanSetup")]
    partial class InitialCleanSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KonferansSalonu.Models.Auditlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("auditlogs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Culture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.ToTable("cultures", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Languagekey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("keyname");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Keyname" }, "keyname")
                        .IsUnique();

                    b.ToTable("languagekeys", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Passwordresettoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Expirationdate")
                        .HasColumnType("datetime")
                        .HasColumnName("expirationdate");

                    b.Property<bool>("Isused")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isused");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Userid" }, "userid");

                    b.ToTable("passwordresettoken", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("capacity")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedat");

                    b.Property<bool>("Isdisabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isdisabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("rooms", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Defaultheight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("defaultheight")
                        .HasDefaultValueSql("'40'");

                    b.Property<int?>("Defaultwidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("defaultwidth")
                        .HasDefaultValueSql("'40'");

                    b.Property<int?>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("height")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Isresize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("isresize")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("label");

                    b.Property<double>("Rotation")
                        .HasColumnType("double")
                        .HasColumnName("rotation");

                    b.Property<int?>("Scalepercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scalepercentage")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("Seatgroupid")
                        .HasColumnType("int")
                        .HasColumnName("seatgroupid");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'1'")
                        .HasComment("1-armchair, 2-chair, 3-table, 4-rectangletable, 5-stage");

                    b.Property<int?>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("width")
                        .HasDefaultValueSql("'0'");

                    b.Property<double>("X")
                        .HasColumnType("double")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Seatgroupid" }, "seats_ibfk_1");

                    b.ToTable("seats", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Seatgroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Sectionid")
                        .HasColumnType("int")
                        .HasColumnName("sectionid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Sectionid" }, "sectionid");

                    b.ToTable("seatgroups", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color")
                        .HasDefaultValueSql("'#FFFFFF'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Roomid")
                        .HasColumnType("int")
                        .HasColumnName("roomid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Roomid" }, "roomid");

                    b.ToTable("section", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cultureid")
                        .HasColumnType("int")
                        .HasColumnName("cultureid");

                    b.Property<int>("Keyid")
                        .HasColumnType("int")
                        .HasColumnName("keyid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cultureid", "Keyid" }, "UQ_Culture_Key")
                        .IsUnique();

                    b.HasIndex(new[] { "Keyid" }, "keyid");

                    b.ToTable("translations", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cultureid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cultureid")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'user'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cultureid" }, "cultureid");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Passwordresettoken", b =>
                {
                    b.HasOne("KonferansSalonu.Models.User", "User")
                        .WithMany("Passwordresettokens")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("passwordresettoken_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Seat", b =>
                {
                    b.HasOne("KonferansSalonu.Models.Seatgroup", "Seatgroup")
                        .WithMany("Seats")
                        .HasForeignKey("Seatgroupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("seats_ibfk_1");

                    b.Navigation("Seatgroup");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Seatgroup", b =>
                {
                    b.HasOne("KonferansSalonu.Models.Section", "Section")
                        .WithMany("Seatgroups")
                        .HasForeignKey("Sectionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seatgroups_ibfk_1");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Section", b =>
                {
                    b.HasOne("KonferansSalonu.Models.Room", "Room")
                        .WithMany("Sections")
                        .HasForeignKey("Roomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("section_ibfk_1");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Translation", b =>
                {
                    b.HasOne("KonferansSalonu.Models.Culture", "Culture")
                        .WithMany("Translations")
                        .HasForeignKey("Cultureid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("translations_ibfk_1");

                    b.HasOne("KonferansSalonu.Models.Languagekey", "Key")
                        .WithMany("Translations")
                        .HasForeignKey("Keyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("translations_ibfk_2");

                    b.Navigation("Culture");

                    b.Navigation("Key");
                });

            modelBuilder.Entity("KonferansSalonu.Models.User", b =>
                {
                    b.HasOne("KonferansSalonu.Models.Culture", "Culture")
                        .WithMany("Users")
                        .HasForeignKey("Cultureid")
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("Culture");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Culture", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Languagekey", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Room", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Seatgroup", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("KonferansSalonu.Models.Section", b =>
                {
                    b.Navigation("Seatgroups");
                });

            modelBuilder.Entity("KonferansSalonu.Models.User", b =>
                {
                    b.Navigation("Passwordresettokens");
                });
#pragma warning restore 612, 618
        }
    }
}
